# Generated by Django 3.1 on 2020-09-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200925_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default_profile.png', upload_to='user/%Y/%m/%d/'),
        ),
    ]
