# Generated by Django 3.1 on 2020-09-26 21:59

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200926_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default_profile.png', upload_to=account.models.get_image_path),
        ),
    ]
