# Generated by Django 3.1.3 on 2020-11-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20201126_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='description',
            field=models.TextField(max_length=800, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
    ]
