# Generated by Django 3.1.3 on 2020-12-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20201128_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='like_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
